/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ClienteControle;
import Modelo.ClienteModelo;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblCodCliente = new javax.swing.JLabel();
        txtCodCliente = new javax.swing.JTextField();
        lblNomCliente = new javax.swing.JLabel();
        txtNomCliente = new javax.swing.JTextField();
        lblRgCliente = new javax.swing.JLabel();
        txtRgCliente = new javax.swing.JTextField();
        lblCpfCliente = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        lblCepCliente = new javax.swing.JLabel();
        txtCepCliente = new javax.swing.JTextField();
        lblEndCliente = new javax.swing.JLabel();
        txtEndCliente = new javax.swing.JTextField();
        lblNumCliente = new javax.swing.JLabel();
        txtNumCliente = new javax.swing.JTextField();
        lblCidCliente = new javax.swing.JLabel();
        txtCidCliente = new javax.swing.JTextField();
        lblEstCliente = new javax.swing.JLabel();
        txtEstCliente = new javax.swing.JTextField();
        lblBaiCliente = new javax.swing.JLabel();
        txtBaiCliente = new javax.swing.JTextField();
        lblRefCliente = new javax.swing.JLabel();
        txtRefCliente = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblTelCliente = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Cliente");

        lblCodCliente.setText("Código");

        txtCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodClienteFocusLost(evt);
            }
        });

        lblNomCliente.setText("Nome");

        lblRgCliente.setText("RG");

        lblCpfCliente.setText("CPF");

        lblCepCliente.setText("CEP");

        lblEndCliente.setText("Endereço");

        lblNumCliente.setText("Número");

        txtNumCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumClienteActionPerformed(evt);
            }
        });

        lblCidCliente.setText("Cidade");

        lblEstCliente.setText("Estado");

        lblBaiCliente.setText("Bairro");

        lblRefCliente.setText("Referência");

        lblEmail.setText("E-mail");

        lblTelCliente.setText("Telefone");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodCliente)
                            .addComponent(lblEndCliente)
                            .addComponent(lblCidCliente)
                            .addComponent(lblRefCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(txtRgCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpfCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNomCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblCepCliente)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtRefCliente, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCidCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEmail)
                                            .addComponent(lblEstCliente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtEstCliente)
                                            .addComponent(txtEmail)))
                                    .addComponent(txtEndCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBaiCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNumCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBaiCliente)
                                    .addComponent(txtNumCliente)
                                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(lblRgCliente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCliente)
                    .addComponent(lblNomCliente)
                    .addComponent(txtNomCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRgCliente)
                            .addComponent(lblCpfCliente)
                            .addComponent(lblCepCliente)
                            .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtRgCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndCliente)
                    .addComponent(lblNumCliente))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaiCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidCliente)
                    .addComponent(lblEstCliente)
                    .addComponent(lblBaiCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRefCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelCliente)
                    .addComponent(lblRefCliente)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnLimpar)
                    .addComponent(btnDeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumClienteActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText().equals("Adicionar")) {
            ClienteControle cliente = new ClienteControle();
            if (cliente.inserirCliente(getDadosFrameCliente())) {
                JOptionPane.showMessageDialog(this,
                        "Incluido com sucesso!",
                        "Manutenção de Cliente",
                        1);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Inclusão não realizada!",
                        "Manutenção de Cliente",
                        0
                );
            }
        } else {
            ClienteControle cliente = new ClienteControle();
            if (cliente.atualizarCliente(getDadosFrameCliente())) {
                JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção de Cliente",1);
            } else {
                JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção de Cliente", 0);
            }
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        ClienteControle cliente = new ClienteControle();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão de Cliente", 1, 1)==0){
            if (cliente.excluirCliente(this.getDadosFrameCliente())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Cliente",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Cliente", 0);
            }
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Cliente", 0);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodClienteFocusLost
        if (!this.txtCodCliente.getText().equals("")) {
            try {
                Integer.parseInt(this.txtCodCliente.getText());
                
                ClienteModelo cliente = new ClienteControle().getCliente(
                    Integer.parseInt(this.txtCodCliente.getText())
                );

                // Pesquisar se Cod. Existe
                if (cliente !=null )
                {
                    this.txtCodCliente.setText(""+cliente.getIdCliente());
                    this.txtNomCliente.setText(cliente.getNome());
                    this.txtRgCliente.setText(cliente.getRg());
                    this.txtCpfCliente.setText(cliente.getCpf());
                    this.txtCepCliente.setText(cliente.getCep());
                    this.txtEndCliente.setText(cliente.getLogradouro());
                    this.txtNumCliente.setText(""+cliente.getNumero());
                    this.txtCidCliente.setText(cliente.getCidade());
                    this.txtEstCliente.setText(cliente.getEstado());
                    this.txtBaiCliente.setText(cliente.getBairro());
                    this.txtRefCliente.setText(cliente.getReferencia());
                    this.txtEmail.setText(cliente.getEmail());
                    this.txtTelCliente.setText(cliente.getTelefone());
                    setStatComponents("edicao");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Cliente não Existe!", "Manutencao de Cliente",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Cliente",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        }
    }//GEN-LAST:event_txtCodClienteFocusLost

    private ClienteModelo getDadosFrameCliente() {
        ClienteModelo cliente = new ClienteModelo();
        cliente.setIdCliente(Integer.parseInt(this.txtCodCliente.getText()));
        cliente.setNome(this.txtNomCliente.getText());
        cliente.setRg(this.txtRgCliente.getText());
        cliente.setCpf(this.txtCpfCliente.getText());
        cliente.setCep(this.txtCepCliente.getText());
        cliente.setLogradouro(this.txtEndCliente.getText());
        cliente.setNumero(Integer.parseInt(this.txtNumCliente.getText()));
        cliente.setCidade(this.txtCidCliente.getText());
        cliente.setEstado(this.txtEstCliente.getText());
        cliente.setBairro(this.txtBaiCliente.getText());
        cliente.setReferencia(this.txtRefCliente.getText());
        cliente.setEmail(this.txtEmail.getText());
        cliente.setTelefone(this.txtTelCliente.getText());
        cliente.setStatus(1);
        
        return cliente;
    }
    
    private void limparCampos() {
        this.txtCodCliente.setText(null);
        this.txtNomCliente.setText(null);
        this.txtRgCliente.setText(null);
        this.txtCpfCliente.setText(null);
        this.txtCepCliente.setText(null);
        this.txtEndCliente.setText(null);
        this.txtNumCliente.setText(null);
        this.txtCidCliente.setText(null);
        this.txtEstCliente.setText(null);
        this.txtBaiCliente.setText(null);
        this.txtRefCliente.setText(null);
        this.txtEmail.setText(null);
        this.txtTelCliente.setText(null);
        this.txtCodCliente.requestFocus();
        setStatComponents("inicio");
    }
    
    private void setStatComponents(String string) {
        if (string.equals("edicao")) {
             this.txtCodCliente.setEnabled(false);
             this.btnAcao.setText("Alterar");
        }
        
        if (string.equals("inicio")) {
             this.txtCodCliente.setEnabled(true);
             this.btnAcao.setText("Adicionar");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblBaiCliente;
    private javax.swing.JLabel lblCepCliente;
    private javax.swing.JLabel lblCidCliente;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndCliente;
    private javax.swing.JLabel lblEstCliente;
    private javax.swing.JLabel lblNomCliente;
    private javax.swing.JLabel lblNumCliente;
    private javax.swing.JLabel lblRefCliente;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBaiCliente;
    private javax.swing.JTextField txtCepCliente;
    private javax.swing.JTextField txtCidCliente;
    private javax.swing.JTextField txtCodCliente;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndCliente;
    private javax.swing.JTextField txtEstCliente;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtNumCliente;
    private javax.swing.JTextField txtRefCliente;
    private javax.swing.JTextField txtRgCliente;
    private javax.swing.JTextField txtTelCliente;
    // End of variables declaration//GEN-END:variables
}
