
package Visao;

import Controle.EmpresaControle;
import Modelo.EmpresaModelo;
import javax.swing.JOptionPane;

public class Empresa extends javax.swing.JFrame {

    public Empresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblCodEmpresa = new javax.swing.JLabel();
        txtNomFantasia = new javax.swing.JTextField();
        lblRazaoSocialEmpresa = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblCnpjEmpresa = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblLogradouroEmpresa = new javax.swing.JLabel();
        txtLogradouroEmpresa = new javax.swing.JTextField();
        lblEmailEmpresa = new javax.swing.JLabel();
        txtEmailEmpresa = new javax.swing.JTextField();
        lblTelefoneEmpresa = new javax.swing.JLabel();
        txtTelEmpresa = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblNomeFantasiaEmpresa = new javax.swing.JLabel();
        txtCodEmpresa = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empresa - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Empresa");

        lblCodEmpresa.setText("Código");

        lblRazaoSocialEmpresa.setText("Razão Social");

        lblCnpjEmpresa.setText("CNPJ");

        lblLogradouroEmpresa.setText("Logradouro");

        lblEmailEmpresa.setText("E-mail");

        lblTelefoneEmpresa.setText("Telefone");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblNomeFantasiaEmpresa.setText("Nome Fantasia");

        txtCodEmpresa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodEmpresaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodEmpresa)
                    .addComponent(lblRazaoSocialEmpresa)
                    .addComponent(lblLogradouroEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLogradouroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEmailEmpresa)
                                .addGap(9, 9, 9)
                                .addComponent(txtEmailEmpresa))
                            .addComponent(txtRazaoSocial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCnpjEmpresa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTelefoneEmpresa, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCnpj)
                            .addComponent(txtTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNomeFantasiaEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodEmpresa)
                    .addComponent(lblNomeFantasiaEmpresa)
                    .addComponent(txtCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRazaoSocialEmpresa)
                    .addComponent(lblCnpjEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogradouroEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefoneEmpresa)
                    .addComponent(lblLogradouroEmpresa)
                    .addComponent(lblEmailEmpresa)
                    .addComponent(txtEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnLimpar)
                    .addComponent(btnDeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText().equals("Adicionar")) {
            EmpresaControle empresa = new EmpresaControle();
            if (empresa.inserirEmpresa(getDadosFrameEmpresa())) {
                JOptionPane.showMessageDialog(this,
                        "Incluido com sucesso!",
                        "Manutenção de Empresa",
                        1);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Inclusão não realizada!",
                        "Manutenção de Empresa",
                        0
                );
            }
        } else {
            EmpresaControle empresa = new EmpresaControle();
            if (empresa.atualizarEmpresa(getDadosFrameEmpresa())) {
                JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção de Empresa",1);
            } else {
                JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção de Empresa", 0);
            }
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        EmpresaControle empresa = new EmpresaControle();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão de Empresa", 1, 1)==0){
            if (empresa.excluirEmpresa(this.getDadosFrameEmpresa())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Empresa",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Empresa", 0);
            }
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Empresa", 0);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodEmpresaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodEmpresaFocusLost
        if (!this.txtCodEmpresa.getText().equals("")) {
            try {
                Integer.parseInt(this.txtCodEmpresa.getText());
                
                EmpresaModelo empresa = new EmpresaControle().getEmpresa(
                    Integer.parseInt(this.txtCodEmpresa.getText())
                );

                // Pesquisar se Cod. Existe
                if (empresa !=null )
                {
                    this.txtCodEmpresa.setText(""+empresa.getCodEmpresa());
                    this.txtNomFantasia.setText(empresa.getNomeFantasia());
                    this.txtRazaoSocial.setText(empresa.getRazaoSocial());
                    this.txtCnpj.setText(empresa.getCnpj());
                    this.txtLogradouroEmpresa.setText(empresa.getEndereco());
                    this.txtEmailEmpresa.setText(empresa.getTelefone());
                    this.txtTelEmpresa.setText(empresa.getEmail());
                    setStatComponents("edicao");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Empresa não Existe!", "Manutencao de Empresa",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Empresa",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        }
    }//GEN-LAST:event_txtCodEmpresaFocusLost

    private EmpresaModelo getDadosFrameEmpresa() {
        EmpresaModelo empresa = new EmpresaModelo();
        empresa.setCodEmpresa(Integer.parseInt(this.txtCodEmpresa.getText()));
        empresa.setNomeFantasia(this.txtNomFantasia.getText());
        empresa.setRazaoSocial(this.txtRazaoSocial.getText());
        empresa.setCnpj(this.txtCnpj.getText());
        empresa.setEndereco(this.txtLogradouroEmpresa.getText());
        empresa.setTelefone(this.txtTelEmpresa.getText());
        empresa.setEmail(this.txtEmailEmpresa.getText());
        
        return empresa;
    }
    
    private void limparCampos() {
        this.txtNomFantasia.setText(null);
        this.txtRazaoSocial.setText(null);
        this.txtCnpj.setText(null);
        this.txtLogradouroEmpresa.setText(null);
        this.txtEmailEmpresa.setText(null);
        this.txtTelEmpresa.setText(null);
        this.txtCodEmpresa.requestFocus();
        setStatComponents("inicio");
    }
    
    private void setStatComponents(String string) {
        if (string.equals("edicao")) {
             this.txtCodEmpresa.setEnabled(false);
             this.btnAcao.setText("Alterar");
        }
        
        if (string.equals("inicio")) {
             this.txtCodEmpresa.setEnabled(true);
             this.btnAcao.setText("Adicionar");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCnpjEmpresa;
    private javax.swing.JLabel lblCodEmpresa;
    private javax.swing.JLabel lblEmailEmpresa;
    private javax.swing.JLabel lblLogradouroEmpresa;
    private javax.swing.JLabel lblNomeFantasiaEmpresa;
    private javax.swing.JLabel lblRazaoSocialEmpresa;
    private javax.swing.JLabel lblTelefoneEmpresa;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtCodEmpresa;
    private javax.swing.JTextField txtEmailEmpresa;
    private javax.swing.JTextField txtLogradouroEmpresa;
    private javax.swing.JTextField txtNomFantasia;
    private javax.swing.JTextField txtRazaoSocial;
    private javax.swing.JTextField txtTelEmpresa;
    // End of variables declaration//GEN-END:variables
}
