
package Visao;

import Controle.FornecedorControle;
import Modelo.FornecedorModelo;
import javax.swing.JOptionPane;

public class Fornecedor extends javax.swing.JFrame {
    
    public Fornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblCodCliente = new javax.swing.JLabel();
        txtCodigoFornecedor = new javax.swing.JTextField();
        lblNomCliente = new javax.swing.JLabel();
        txtNomeFantFornecedor = new javax.swing.JTextField();
        lblRgCliente = new javax.swing.JLabel();
        txtCnpjFornecedor = new javax.swing.JTextField();
        lblCpfCliente = new javax.swing.JLabel();
        txtRazaoSocialFornecedor = new javax.swing.JTextField();
        lblEndCliente = new javax.swing.JLabel();
        txtEnderecoFornecedor = new javax.swing.JTextField();
        lblNumCliente = new javax.swing.JLabel();
        txtTelefoneFornecedor = new javax.swing.JTextField();
        lblCidCliente = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Fornecedor");

        lblCodCliente.setText("Código");

        txtCodigoFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodigoFornecedorFocusLost(evt);
            }
        });

        lblNomCliente.setText("Nome Fantasia");

        lblRgCliente.setText("CNPJ");

        lblCpfCliente.setText("Razão Social");

        lblEndCliente.setText("Endereço");

        lblNumCliente.setText("Telefone");

        txtTelefoneFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneFornecedorActionPerformed(evt);
            }
        });

        lblCidCliente.setText("E-mail");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodCliente)
                    .addComponent(lblEndCliente)
                    .addComponent(lblCidCliente)
                    .addComponent(lblRgCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtCnpjFornecedor))
                        .addGap(10, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCpfCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNomCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNomeFantFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(txtRazaoSocialFornecedor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEnderecoFornecedor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(lblTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lblTitulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCliente)
                    .addComponent(lblNomCliente)
                    .addComponent(txtNomeFantFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCpfCliente)
                            .addComponent(txtRazaoSocialFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRgCliente))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndCliente)
                    .addComponent(lblNumCliente))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnLimpar)
                    .addComponent(btnDeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefoneFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneFornecedorActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText().equals("Salvar")) {
            FornecedorControle fornecedor = new FornecedorControle();
            if (fornecedor.inserirFornecedor(getDadosFrameFornecedor())) {
                JOptionPane.showMessageDialog(this,
                        "Incluido com sucesso!",
                        "Manutenção de Fornecedor",
                        1);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Inclusão não realizada!",
                        "Manutenção de Fornecedor",
                        0
                );
            }
        } else {
            FornecedorControle fornecedor = new FornecedorControle();
            if (fornecedor.atualizarFornecedor(getDadosFrameFornecedor())) {
                JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção de Fornecedor",1);
            } else {
                JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção de Fornecedor", 0);
            }
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        FornecedorControle fornecedor = new FornecedorControle();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão de Fornecedor", 1, 1)==0){
            if (fornecedor.excluirFornecedor(this.getDadosFrameFornecedor())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Fornecedor",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Fornecedor", 0);
            }
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Fornecedor", 0);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodigoFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodigoFornecedorFocusLost
        if (!this.txtCodigoFornecedor.getText().equals("")) {
            try {
                Integer.parseInt(this.txtCodigoFornecedor.getText());
                
                FornecedorModelo fornecedor = new FornecedorControle().obterFornecedor(
                    Integer.parseInt(this.txtCodigoFornecedor.getText())
                );

                // Pesquisar se Cod. Existe
                if (fornecedor !=null )
                {
                    this.txtCodigoFornecedor.setText(""+fornecedor.getCodFornecedor());
                    this.txtNomeFantFornecedor.setText(fornecedor.getNomeFantasia());
                    this.txtCnpjFornecedor.setText(fornecedor.getCnpj());
                    this.txtRazaoSocialFornecedor.setText(fornecedor.getRazaoSocial());
                    this.txtEnderecoFornecedor.setText(fornecedor.getEndereco());
                    this.txtTelefoneFornecedor.setText(fornecedor.getTelefone());
                    this.txtEmailFornecedor.setText(fornecedor.getEmail());
                    setStatComponents("edicao");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Fornecedor não Existe!", "Manutencao de Fornecedor",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Fornecedor",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        }
    }//GEN-LAST:event_txtCodigoFornecedorFocusLost

    private FornecedorModelo getDadosFrameFornecedor() {
        FornecedorModelo fornecedor = new FornecedorModelo();
        fornecedor.setCodFornecedor(Integer.parseInt(this.txtCodigoFornecedor.getText()));
        fornecedor.setNomeFantasia(this.txtNomeFantFornecedor.getText());
        fornecedor.setCnpj(this.txtCnpjFornecedor.getText());
        fornecedor.setRazaoSocial(this.txtRazaoSocialFornecedor.getText());
        fornecedor.setEndereco(this.txtEnderecoFornecedor.getText());
        fornecedor.setTelefone(this.txtTelefoneFornecedor.getText());
        fornecedor.setEmail(this.txtEmailFornecedor.getText());
        
        return fornecedor;
    }
    
    private void limparCampos() {
        this.txtCodigoFornecedor.setText(null);
        this.txtNomeFantFornecedor.setText(null);
        this.txtCnpjFornecedor.setText(null);
        this.txtRazaoSocialFornecedor.setText(null);
        this.txtEnderecoFornecedor.setText(null);
        this.txtTelefoneFornecedor.setText(null);
        this.txtEmailFornecedor.setText(null);
        this.txtCodigoFornecedor.requestFocus();
        setStatComponents("inicio");
    }
    
    private void setStatComponents(String string) {
        if (string.equals("edicao")) {
             this.txtCodigoFornecedor.setEnabled(false);
             this.btnAcao.setText("Alterar");
        }
        
        if (string.equals("inicio")) {
             this.txtCodigoFornecedor.setEnabled(true);
             this.btnAcao.setText("Salvar");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lblCidCliente;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblEndCliente;
    private javax.swing.JLabel lblNomCliente;
    private javax.swing.JLabel lblNumCliente;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCnpjFornecedor;
    private javax.swing.JTextField txtCodigoFornecedor;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtEnderecoFornecedor;
    private javax.swing.JTextField txtNomeFantFornecedor;
    private javax.swing.JTextField txtRazaoSocialFornecedor;
    private javax.swing.JTextField txtTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
