
package Visao;

import Controle.EmpresaControle;
import Controle.FuncionarioControle;
import Modelo.EmpresaModelo;
import Modelo.FuncionarioModelo;
import Modelo.UsuarioModelo;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class Funcionario extends javax.swing.JFrame {
    
    public Funcionario() {
        initComponents();
        iniciaComboBoxEmpresa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        lblCodCliente = new javax.swing.JLabel();
        txtCodFunc = new javax.swing.JTextField();
        lblNomCliente = new javax.swing.JLabel();
        txtNomFunc = new javax.swing.JTextField();
        lblRgCliente = new javax.swing.JLabel();
        txtCepFunc = new javax.swing.JTextField();
        lblCpfCliente = new javax.swing.JLabel();
        txtCpfFunc = new javax.swing.JTextField();
        lblEndCliente = new javax.swing.JLabel();
        txtEndFunc = new javax.swing.JTextField();
        lblNumCliente = new javax.swing.JLabel();
        txtNumFunc = new javax.swing.JTextField();
        lblCidCliente = new javax.swing.JLabel();
        txtCidFunc = new javax.swing.JTextField();
        lblEstCliente = new javax.swing.JLabel();
        txtEstFunc = new javax.swing.JTextField();
        lblBaiCliente = new javax.swing.JLabel();
        txtBaiFunc = new javax.swing.JTextField();
        lblRefCliente = new javax.swing.JLabel();
        txtChapaFunc = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailFunc = new javax.swing.JTextField();
        lblTelCliente = new javax.swing.JLabel();
        txtTelFunc = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        txtCargoFunc = new javax.swing.JTextField();
        lblRefCliente1 = new javax.swing.JLabel();
        lblRefCliente2 = new javax.swing.JLabel();
        txtSalarioFunc = new javax.swing.JTextField();
        lblRefCliente3 = new javax.swing.JLabel();
        cjbEmpresa = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        lblUsuarioFunc = new javax.swing.JLabel();
        txtUsuarioFunc = new javax.swing.JTextField();
        txtSenhaFunc = new javax.swing.JTextField();
        lblSenhaFunc = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Funcionario - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de Funcionário");

        lblCodCliente.setText("Código");

        txtCodFunc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodFuncFocusLost(evt);
            }
        });

        lblNomCliente.setText("Nome");

        lblRgCliente.setText("CEP");

        lblCpfCliente.setText("CPF");

        lblEndCliente.setText("Endereço");

        lblNumCliente.setText("Número");

        txtNumFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumFuncActionPerformed(evt);
            }
        });

        lblCidCliente.setText("Cidade");

        lblEstCliente.setText("Estado");

        lblBaiCliente.setText("Bairro");

        lblRefCliente.setText("Chapa");

        lblEmail.setText("E-mail");

        lblTelCliente.setText("Telefone");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblRefCliente1.setText("Cargo");

        lblRefCliente2.setText("Salario");

        lblRefCliente3.setText("Empresa");

        lblUsuarioFunc.setText("Usuário");

        lblSenhaFunc.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcao)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar)
                .addGap(265, 265, 265))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCodCliente)
                    .addComponent(lblEndCliente)
                    .addComponent(lblCidCliente)
                    .addComponent(lblRgCliente)
                    .addComponent(lblRefCliente)
                    .addComponent(lblRefCliente1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblEstCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstFunc))
                            .addComponent(txtEndFunc))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBaiCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNumCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBaiFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(txtNumFunc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtChapaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmailFunc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblTelCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(lblRefCliente2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRefCliente3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(cjbEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtCepFunc))
                        .addGap(11, 11, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCpfCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblNomCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNomFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(163, 163, 163)))))))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblSenhaFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblUsuarioFunc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsuarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodCliente)
                    .addComponent(lblNomCliente)
                    .addComponent(txtNomFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCpfCliente)
                            .addComponent(txtCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCepFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRgCliente))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEndCliente)
                    .addComponent(lblNumCliente))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaiFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCidCliente)
                    .addComponent(lblEstCliente)
                    .addComponent(lblBaiCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChapaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelCliente)
                    .addComponent(lblRefCliente)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRefCliente1)
                    .addComponent(txtSalarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRefCliente2)
                    .addComponent(lblRefCliente3)
                    .addComponent(cjbEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuarioFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenhaFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSenhaFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnLimpar)
                    .addComponent(btnDeletar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumFuncActionPerformed

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText().equals("Adicionar")) {
            FuncionarioControle func = new FuncionarioControle();
            
            //cadastro apenas de funcionario
            if (this.txtUsuarioFunc.getText().isEmpty() && this.txtSenhaFunc.getText().isEmpty()) {
                if (func.inserirFuncionario(getDadosFrameFuncionario())) {
                    JOptionPane.showMessageDialog(this,"Incluido com sucesso!","Manutenção de Funcionario",1);
                } else {
                    JOptionPane.showMessageDialog(this,"Inclusão não realizada!","Manutenção de Funcionario",0);
                }
            }
            //cadastro de funcionario com usuario (login e senha)
            else {
                if (func.inserirFuncionarioComLogin(getDadosFrameFuncionario(), getDadosFrameUsuario())) {
                    JOptionPane.showMessageDialog(this,"Incluido com sucesso!","Manutenção de Funcionario",1);
                } else {
                    JOptionPane.showMessageDialog(this,"Inclusão não realizada!","Manutenção de Funcionario",0);
                }
            }
            
        } else {
            FuncionarioControle func = new FuncionarioControle();
            if (func.atualizarFuncionario(getDadosFrameFuncionario())) {
                JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção de Funcionario",1);
            } else {
                JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção de Funcionario", 0);
            }
        }
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        FuncionarioControle func = new FuncionarioControle();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão de Funcionario", 1, 1)==0){
            if (func.excluirFuncionario(this.getDadosFrameFuncionario())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Funcionario",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Funcionario", 0);
            }
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Funcionario", 0);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtCodFuncFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodFuncFocusLost
        if (!this.txtCodFunc.getText().equals("")) {
            try {
                Integer.parseInt(this.txtCodFunc.getText());
                
                FuncionarioModelo func = new FuncionarioControle().getFuncionario(
                    Integer.parseInt(this.txtCodFunc.getText())
                );

                // Pesquisar se Cod. Existe
                if (func !=null )
                {
                    this.txtCodFunc.setText(""+func.getIdFuncionario());
                    this.txtNomFunc.setText(func.getNome());
                    this.txtCepFunc.setText(func.getCep());
                    this.txtCpfFunc.setText(func.getCpf());
                    this.txtEndFunc.setText(func.getLogradouro());
                    this.txtNumFunc.setText(""+func.getNumero());
                    this.txtCidFunc.setText(func.getCidade());
                    this.txtEstFunc.setText(func.getEstado());
                    this.txtBaiFunc.setText(func.getBairro());
                    this.txtEmailFunc.setText(func.getEmail());
                    this.txtTelFunc.setText(func.getTelefone());
                    this.txtChapaFunc.setText(func.getChapa());
                    this.txtCargoFunc.setText(func.getCargo());
                    this.txtSalarioFunc.setText(""+func.getSalario());
                    this.cjbEmpresa.setSelectedItem(""+func.getIdEmpresa());
                    //usuario
                    //this.txtUsuarioFunc.setText("");
                    //this.txtSenhaFunc.setText("");
                    
                    setStatComponents("edicao");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Funcionario não Existe!", "Manutencao de Funcionario",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Funcionario",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        }
    }//GEN-LAST:event_txtCodFuncFocusLost

    private FuncionarioModelo getDadosFrameFuncionario() {
        FuncionarioModelo func = new FuncionarioModelo();
        func.setIdFuncionario(Integer.parseInt(this.txtCodFunc.getText()));
        func.setNome(this.txtNomFunc.getText());
        func.setCpf(this.txtCpfFunc.getText());
        func.setCep(this.txtCepFunc.getText());
        func.setLogradouro(this.txtEndFunc.getText());
        func.setNumero(Integer.parseInt(this.txtNumFunc.getText()));
        func.setCidade(this.txtCidFunc.getText());
        func.setEstado(this.txtEstFunc.getText());
        func.setBairro(this.txtBaiFunc.getText());
        func.setEmail(this.txtEmailFunc.getText());
        func.setTelefone(this.txtTelFunc.getText());
        func.setCargo(this.txtCargoFunc.getText());
        func.setChapa(this.txtChapaFunc.getText());
        func.setSalario(Float.parseFloat(this.txtSalarioFunc.getText()));
        func.setIdEmpresa(Integer.parseInt(this.cjbEmpresa.getSelectedItem().toString()));
        
        return func;
    }
    
    private UsuarioModelo getDadosFrameUsuario() {
        UsuarioModelo user = new UsuarioModelo();
        user.setIdFuncionario(Integer.parseInt(this.txtCodFunc.getText()));
        user.setLogin(this.txtUsuarioFunc.getText());
        user.setSenha(this.txtSenhaFunc.getText());
        
        return user;
    }
    
    private void limparCampos() {
        this.txtCodFunc.setText(null);
        this.txtNomFunc.setText(null);
        this.txtCepFunc.setText(null);
        this.txtCpfFunc.setText(null);
        this.txtCepFunc.setText(null);
        this.txtEndFunc.setText(null);
        this.txtNumFunc.setText(null);
        this.txtCidFunc.setText(null);
        this.txtEstFunc.setText(null);
        this.txtBaiFunc.setText(null);
        this.txtChapaFunc.setText(null);
        this.txtEmailFunc.setText(null);
        this.txtTelFunc.setText(null);
        this.txtSalarioFunc.setText(null);
        this.txtCargoFunc.setText(null);
        this.txtCodFunc.requestFocus();
        setStatComponents("inicio");
    }
    
    private void setStatComponents(String string) {
        if (string.equals("edicao")) {
            this.txtCodFunc.setEnabled(false);
            this.btnAcao.setText("Alterar");
            this.txtUsuarioFunc.setVisible(false);
            this.txtSenhaFunc.setVisible(false);
            this.lblUsuarioFunc.setVisible(false);
            this.lblSenhaFunc.setVisible(false);
        }
        
        if (string.equals("inicio")) {
            this.txtCodFunc.setEnabled(true);
            this.btnAcao.setText("Adicionar");
            this.txtUsuarioFunc.setVisible(true);
            this.txtSenhaFunc.setVisible(true);
            this.lblUsuarioFunc.setVisible(true);
            this.lblSenhaFunc.setVisible(true);
        }
    }
    
    private void iniciaComboBoxEmpresa() {
        ArrayList<EmpresaModelo> listaEmpresas = new ArrayList<EmpresaModelo>();
        listaEmpresas = new EmpresaControle().getListaEmpresas();
        
        for (int i=0;i<=listaEmpresas.size()-1;i++){
            this.cjbEmpresa.addItem(""+listaEmpresas.get(i).getCodEmpresa());
        }
        
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cjbEmpresa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBaiCliente;
    private javax.swing.JLabel lblCidCliente;
    private javax.swing.JLabel lblCodCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEndCliente;
    private javax.swing.JLabel lblEstCliente;
    private javax.swing.JLabel lblNomCliente;
    private javax.swing.JLabel lblNumCliente;
    private javax.swing.JLabel lblRefCliente;
    private javax.swing.JLabel lblRefCliente1;
    private javax.swing.JLabel lblRefCliente2;
    private javax.swing.JLabel lblRefCliente3;
    private javax.swing.JLabel lblRgCliente;
    private javax.swing.JLabel lblSenhaFunc;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuarioFunc;
    private javax.swing.JTextField txtBaiFunc;
    private javax.swing.JTextField txtCargoFunc;
    private javax.swing.JTextField txtCepFunc;
    private javax.swing.JTextField txtChapaFunc;
    private javax.swing.JTextField txtCidFunc;
    private javax.swing.JTextField txtCodFunc;
    private javax.swing.JTextField txtCpfFunc;
    private javax.swing.JTextField txtEmailFunc;
    private javax.swing.JTextField txtEndFunc;
    private javax.swing.JTextField txtEstFunc;
    private javax.swing.JTextField txtNomFunc;
    private javax.swing.JTextField txtNumFunc;
    private javax.swing.JTextField txtSalarioFunc;
    private javax.swing.JTextField txtSenhaFunc;
    private javax.swing.JTextField txtTelFunc;
    private javax.swing.JTextField txtUsuarioFunc;
    // End of variables declaration//GEN-END:variables
}
