/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author silva
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuBar = new javax.swing.JMenuBar();
        mnuArquivo = new javax.swing.JMenu();
        mnuItemSair = new javax.swing.JMenuItem();
        mnuCadastrar = new javax.swing.JMenu();
        mnuCadCliente = new javax.swing.JMenuItem();
        mnuCadProduto = new javax.swing.JMenuItem();
        mnuCadVenda = new javax.swing.JMenuItem();
        mnuCadUsuario = new javax.swing.JMenuItem();
        mnuCadEmpresa = new javax.swing.JMenuItem();
        mnuCadFuncionario = new javax.swing.JMenuItem();
        mnuConsulta = new javax.swing.JMenu();
        mnuConCliente = new javax.swing.JMenuItem();
        mnuConProduto = new javax.swing.JMenuItem();
        mnuConVenda = new javax.swing.JMenuItem();
        mnuConEmpresa = new javax.swing.JMenuItem();
        mnuConFuncionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Softmusic - Início");

        mnuArquivo.setText("Arquivo");

        mnuItemSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        mnuItemSair.setText("Sair");
        mnuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemSairActionPerformed(evt);
            }
        });
        mnuArquivo.add(mnuItemSair);

        mnuBar.add(mnuArquivo);

        mnuCadastrar.setText("Cadastrar");

        mnuCadCliente.setText("Cliente");
        mnuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadClienteActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadCliente);

        mnuCadProduto.setText("Produto");
        mnuCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadProdutoActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadProduto);

        mnuCadVenda.setText("Venda");
        mnuCadVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadVendaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadVenda);

        mnuCadUsuario.setText("Usuário");
        mnuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadUsuarioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadUsuario);

        mnuCadEmpresa.setText("Empresa");
        mnuCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadEmpresaActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadEmpresa);

        mnuCadFuncionario.setText("Funcionario");
        mnuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastrar.add(mnuCadFuncionario);

        mnuBar.add(mnuCadastrar);

        mnuConsulta.setText("Consulta");

        mnuConCliente.setText("Cliente");
        mnuConCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConClienteActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuConCliente);

        mnuConProduto.setText("Produto");
        mnuConProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConProdutoActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuConProduto);

        mnuConVenda.setText("Venda");
        mnuConVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConVendaActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuConVenda);

        mnuConEmpresa.setText("Empresa");
        mnuConEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConEmpresaActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuConEmpresa);

        mnuConFuncionario.setText("Funcionário");
        mnuConFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConFuncionarioActionPerformed(evt);
            }
        });
        mnuConsulta.add(mnuConFuncionario);

        mnuBar.add(mnuConsulta);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuItemSairActionPerformed

    private void mnuCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadProdutoActionPerformed
        Produto ViewProcuct = new Produto();
        ViewProcuct.setLocationRelativeTo(null); // Centraliza janela
        ViewProcuct.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadProdutoActionPerformed

    private void mnuCadVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadVendaActionPerformed
        Venda ViewSale = new Venda();
        ViewSale.setLocationRelativeTo(null); // Centraliza janela
        ViewSale.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadVendaActionPerformed

    private void mnuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadClienteActionPerformed
        Cliente ViewCustomer = new Cliente();
        ViewCustomer.setLocationRelativeTo(null); // Centraliza janela
        ViewCustomer.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadClienteActionPerformed

    private void mnuConProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConProdutoActionPerformed
        ProdutoListar ViewProductList = new ProdutoListar();
        ViewProductList.setLocationRelativeTo(null); // Centraliza janela
        ViewProductList.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuConProdutoActionPerformed

    private void mnuConClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConClienteActionPerformed
        ClienteListar ViewCustomerList = new ClienteListar();
        ViewCustomerList.setLocationRelativeTo(null); // Centraliza janela
        ViewCustomerList.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuConClienteActionPerformed

    private void mnuConVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConVendaActionPerformed
        VendaListar ViewSaleList = new VendaListar();
        ViewSaleList.setLocationRelativeTo(null); // Centraliza janela
        ViewSaleList.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuConVendaActionPerformed

    private void mnuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadUsuarioActionPerformed
        Usuario ViewUser = new Usuario();
        ViewUser.setLocationRelativeTo(null); // Centraliza janela
        ViewUser.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadUsuarioActionPerformed

    private void mnuCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadEmpresaActionPerformed
        Empresa ViewCompany = new Empresa();
        ViewCompany.setLocationRelativeTo(null); // Centraliza janela
        ViewCompany.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadEmpresaActionPerformed

    private void mnuConEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConEmpresaActionPerformed
        EmpresaListar ViewCompany = new EmpresaListar();
        ViewCompany.setLocationRelativeTo(null); // Centraliza janela
        ViewCompany.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuConEmpresaActionPerformed

    private void mnuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadFuncionarioActionPerformed
        Funcionario ViewEmployee = new Funcionario();
        ViewEmployee.setLocationRelativeTo(null); // Centraliza janela
        ViewEmployee.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuCadFuncionarioActionPerformed

    private void mnuConFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConFuncionarioActionPerformed
        FuncionarioListar ViewEmployee = new FuncionarioListar();
        ViewEmployee.setLocationRelativeTo(null); // Centraliza janela
        ViewEmployee.setVisible(true); // Abre janela
    }//GEN-LAST:event_mnuConFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu mnuArquivo;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenuItem mnuCadCliente;
    private javax.swing.JMenuItem mnuCadEmpresa;
    private javax.swing.JMenuItem mnuCadFuncionario;
    private javax.swing.JMenuItem mnuCadProduto;
    private javax.swing.JMenuItem mnuCadUsuario;
    private javax.swing.JMenuItem mnuCadVenda;
    private javax.swing.JMenu mnuCadastrar;
    private javax.swing.JMenuItem mnuConCliente;
    private javax.swing.JMenuItem mnuConEmpresa;
    private javax.swing.JMenuItem mnuConFuncionario;
    private javax.swing.JMenuItem mnuConProduto;
    private javax.swing.JMenuItem mnuConVenda;
    private javax.swing.JMenu mnuConsulta;
    private javax.swing.JMenuItem mnuItemSair;
    // End of variables declaration//GEN-END:variables
}
