/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ProdutoControle;
import Modelo.ProdutoModelo;
import javax.swing.JOptionPane;
import java.util.ArrayList;


/**
 *
 * @author silva
 */
public class Produto extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    public Produto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCodProduto = new javax.swing.JLabel();
        txtCodProduto = new javax.swing.JTextField();
        lblNomProduto = new javax.swing.JLabel();
        txtNomProduto = new javax.swing.JTextField();
        lblCodBarProduto = new javax.swing.JLabel();
        txtCodBarProduto = new javax.swing.JTextField();
        lblDescProduto = new javax.swing.JLabel();
        txtDescProduto = new javax.swing.JTextField();
        lblMarcaProduto = new javax.swing.JLabel();
        txtMarcaProduto = new javax.swing.JTextField();
        lblCatProduto = new javax.swing.JLabel();
        txtCatProduto = new javax.swing.JTextField();
        lblFornProduto = new javax.swing.JLabel();
        cbFornecedor = new javax.swing.JComboBox<>();
        lblQtdProduto = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JTextField();
        lblTotEstProduto = new javax.swing.JLabel();
        txtTotEstProduto = new javax.swing.JTextField();
        lblPrecoCompraProduto = new javax.swing.JLabel();
        txtPrecoCompraProduto = new javax.swing.JTextField();
        lblPrecoVendaProduto = new javax.swing.JLabel();
        txtPrecoVendaProduto = new javax.swing.JTextField();
        btnAcao = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de produto");

        lblCodProduto.setText("Código");

        txtCodProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodProdutoFocusLost(evt);
            }
        });

        lblNomProduto.setText("Nome");

        lblCodBarProduto.setText("Código de barras");

        lblDescProduto.setText("Descrição");

        lblMarcaProduto.setText("Marca");

        lblCatProduto.setText("Categoria");

        lblFornProduto.setText("Fornecedor");

        lblQtdProduto.setText("Quantidade");

        lblTotEstProduto.setText("Total do estoque");

        lblPrecoCompraProduto.setText("Preço de compra");

        lblPrecoVendaProduto.setText("Preço de venda");

        btnAcao.setText("Salvar");
        btnAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcaoActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCodProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomProduto)
                                    .addComponent(txtNomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQtdProduto, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDescProduto)
                                    .addComponent(lblQtdProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTotEstProduto)
                                    .addComponent(lblMarcaProduto)
                                    .addComponent(txtMarcaProduto)
                                    .addComponent(txtTotEstProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCatProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtPrecoCompraProduto)
                                    .addComponent(lblCodBarProduto)
                                    .addComponent(lblCatProduto)
                                    .addComponent(lblPrecoCompraProduto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblPrecoVendaProduto)
                                    .addComponent(lblFornProduto)
                                    .addComponent(txtPrecoVendaProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(cbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(txtCodBarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAcao)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpar)
                        .addGap(149, 149, 149)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitulo)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodProduto)
                    .addComponent(lblNomProduto)
                    .addComponent(lblCodBarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodBarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescProduto)
                    .addComponent(lblMarcaProduto)
                    .addComponent(lblCatProduto)
                    .addComponent(lblFornProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCatProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdProduto)
                    .addComponent(lblTotEstProduto)
                    .addComponent(lblPrecoCompraProduto)
                    .addComponent(lblPrecoVendaProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotEstProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoCompraProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoVendaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcao)
                    .addComponent(btnDeletar)
                    .addComponent(btnLimpar))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcaoActionPerformed
        if (btnAcao.getText().equals("Salvar")) {
            ProdutoControle produto = new ProdutoControle();
            if (produto.inserirProduto(getDadosFrameProduto())) {
                JOptionPane.showMessageDialog(this,
                        "Incluido com sucesso!",
                        "Manutenção de Produto",
                        1);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Inclusão não realizada!",
                        "Manutenção de Produto",
                        0
                );
            }
        } 
        else {
            ProdutoControle produto = new ProdutoControle();
            if (produto.atualizarProduto(getDadosFrameProduto())) {
                JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção de Produto",1);
            } else {
                JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção de Produto", 0);
            }
        };
    }//GEN-LAST:event_btnAcaoActionPerformed

    private void txtCodProdutoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodProdutoFocusLost
        if (!this.txtCodProduto.getText().equals("")) {
            try {
                Integer.parseInt(this.txtCodProduto.getText());
                
                ProdutoModelo produto = new ProdutoControle().obterProduto(
                    Integer.parseInt(this.txtCodProduto.getText())
                );

                // Pesquisar se Cod. Existe
                if (produto !=null )
                {
                    this.txtCodProduto.setText(""+produto.getIdProduto());
                    this.txtNomProduto.setText(produto.getNome());
                    this.txtCodBarProduto.setText(produto.getCodigoBarra());
                    this.txtDescProduto.setText(produto.getDescricao());
                    this.txtMarcaProduto.setText(produto.getMarca());
                    this.txtCatProduto.setText(produto.getCategoria());
                    this.cbFornecedor.setSelectedItem(""+produto.getIdFornecedor());
                    this.txtQtdProduto.setText(""+produto.getQuantidadeMin());
                    this.txtTotEstProduto.setText(""+produto.getQuantidadeEstoq());
                    this.txtPrecoCompraProduto.setText(""+produto.getPrecoCompra());
                    this.txtPrecoVendaProduto.setText(""+produto.getPrecoVenda());
                    setStatComponents("edicao");
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Produto não Existe!", "Manutencao de Produto",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Produto",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        }
    }//GEN-LAST:event_txtCodProdutoFocusLost

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        ProdutoControle produto = new ProdutoControle();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão do Produto", 1, 1)==0){
            if (produto.excluirProduto(this.getDadosFrameProduto())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção de Produto",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção de Produto", 0);
            }
            this.limparCampos();
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção de Produto", 0);
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private ProdutoModelo getDadosFrameProduto() {
        ProdutoModelo produto = new ProdutoModelo();
        produto.setIdProduto(Integer.parseInt(this.txtCodProduto.getText()));
        produto.setNome(this.txtNomProduto.getText());
        produto.setCodigoBarra(this.txtCodBarProduto.getText());
        produto.setDescricao(this.txtDescProduto.getText());
        produto.setMarca(this.txtMarcaProduto.getText());
        produto.setCategoria(this.txtCatProduto.getText());
        produto.setIdFornecedor(Integer.parseInt(this.cbFornecedor.getSelectedItem().toString()));
        produto.setQuantidadeMin(Integer.parseInt(this.txtQtdProduto.getText()));
        produto.setQuantidadeEstoq(Integer.parseInt(this.txtTotEstProduto.getText()));
        produto.setPrecoCompra(Float.parseFloat(this.txtPrecoCompraProduto.getText()));
        produto.setPrecoVenda(Float.parseFloat(this.txtPrecoVendaProduto.getText()));
        
        return produto;
    }
    
    // Limpa campos do formulário
    private void limparCampos() {
        this.txtCodProduto.setText("");
        this.txtNomProduto.setText("");
        this.txtCodBarProduto.setText("");
        this.txtDescProduto.setText("");
        this.txtMarcaProduto.setText("");
        this.txtCatProduto.setText("");
        this.txtQtdProduto.setText("");
        this.txtTotEstProduto.setText("");
        this.txtPrecoCompraProduto.setText("");
        this.txtPrecoVendaProduto.setText("");
        this.txtCodProduto.requestFocus();
        setStatComponents("inicio");
    }
    
    // Muda o status dos componentes
    private void setStatComponents(String string) {
        if (string.equals("edicao")) {
             this.txtCodProduto.setEnabled(false);
             this.btnAcao.setText("Alterar");
        }
        
        if (string.equals("inicio")) {
             this.txtCodProduto.setEnabled(true);
             this.btnAcao.setText("Salvar");
        }
    }
    
    private void iniciaComboBoxFornecedor() {
        ArrayList<ProdutoModelo> listaFornecedores = new ArrayList<ProdutoModelo>();
        listaFornecedores = new ProdutoControle().listarProduto();
        
        for (int i=0;i<=listaFornecedores.size()-1;i++){
            this.cbFornecedor.addItem(""+listaFornecedores.get(i).getIdFornecedor());
        }        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcao;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JComboBox<String> cbFornecedor;
    private javax.swing.JLabel lblCatProduto;
    private javax.swing.JLabel lblCodBarProduto;
    private javax.swing.JLabel lblCodProduto;
    private javax.swing.JLabel lblDescProduto;
    private javax.swing.JLabel lblFornProduto;
    private javax.swing.JLabel lblMarcaProduto;
    private javax.swing.JLabel lblNomProduto;
    private javax.swing.JLabel lblPrecoCompraProduto;
    private javax.swing.JLabel lblPrecoVendaProduto;
    private javax.swing.JLabel lblQtdProduto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotEstProduto;
    private javax.swing.JTextField txtCatProduto;
    private javax.swing.JTextField txtCodBarProduto;
    private javax.swing.JTextField txtCodProduto;
    private javax.swing.JTextField txtDescProduto;
    private javax.swing.JTextField txtMarcaProduto;
    private javax.swing.JTextField txtNomProduto;
    private javax.swing.JTextField txtPrecoCompraProduto;
    private javax.swing.JTextField txtPrecoVendaProduto;
    private javax.swing.JTextField txtQtdProduto;
    private javax.swing.JTextField txtTotEstProduto;
    // End of variables declaration//GEN-END:variables
}
