/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ClienteControle;
import Modelo.ClienteModelo;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author silva
 */
public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Sale
     */
    public Venda() {
        initComponents();
        iniciaComboBoxFornecedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblVendedorVenda = new javax.swing.JLabel();
        txtVendedorVenda = new javax.swing.JTextField();
        lblClienteVenda = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox<>();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblEndVenda = new javax.swing.JLabel();
        txtEndVenda = new javax.swing.JTextField();
        lblNumVenda = new javax.swing.JLabel();
        txtNumVenda = new javax.swing.JTextField();
        lblCidadeVenda = new javax.swing.JLabel();
        txtCidadeVenda = new javax.swing.JTextField();
        lblEstadoVenda = new javax.swing.JLabel();
        txtEstadoVenda = new javax.swing.JTextField();
        lblBairroVenda = new javax.swing.JLabel();
        txtBairroVenda = new javax.swing.JTextField();
        lblRefVenda = new javax.swing.JLabel();
        txtRefVenda = new javax.swing.JTextField();
        lblTelVenda = new javax.swing.JLabel();
        txtTelVenda = new javax.swing.JTextField();
        lblCodBarVenda = new javax.swing.JLabel();
        txtCodBarVenda = new javax.swing.JTextField();
        lblQtdVenda = new javax.swing.JLabel();
        txtQtdVenda = new javax.swing.JTextField();
        lblVlrUnitVenda = new javax.swing.JLabel();
        txtVlrUnitVenda = new javax.swing.JTextField();
        lblSubTotVenda = new javax.swing.JLabel();
        txtSubTotVenda = new javax.swing.JTextField();
        chkTodosVenda = new javax.swing.JCheckBox();
        pnTblItensVenda = new javax.swing.JScrollPane();
        tblItensVenda = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblTotalVenda = new javax.swing.JLabel();
        txtTotalVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda - Salvar");

        lblTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        lblTitulo.setText("Cadastro de venda");

        lblVendedorVenda.setText("Vendedor");

        lblClienteVenda.setText("Cliente");

        cbCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbClienteFocusLost(evt);
            }
        });

        lblNome.setText("Nome");

        lblEndVenda.setText("Endereço");

        lblNumVenda.setText("Número");

        lblCidadeVenda.setText("Cidade");

        lblEstadoVenda.setText("Estado");

        lblBairroVenda.setText("Bairro");

        lblRefVenda.setText("Referência");

        lblTelVenda.setText("Telefone");

        lblCodBarVenda.setText("Cód. Barra");

        lblQtdVenda.setText("Quantidade");

        lblVlrUnitVenda.setText("Valor unitário");

        lblSubTotVenda.setText("Sub-total");

        chkTodosVenda.setText("Todos");

        tblItensVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Retirar", "Código", "Produto", "Quantidade", "Valor", "Sub-total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        pnTblItensVenda.setViewportView(tblItensVenda);

        btnConfirmar.setText("OK");

        btnSalvar.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");

        btnLimpar.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblTotalVenda.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(lblTitulo)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVendedorVenda)
                                    .addComponent(lblClienteVenda)
                                    .addComponent(lblEndVenda)
                                    .addComponent(lblCidadeVenda)
                                    .addComponent(lblRefVenda)
                                    .addComponent(lblCodBarVenda)
                                    .addComponent(lblQtdVenda))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pnTblItensVenda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(chkTodosVenda)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtRefVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblNome)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtNome))
                                                        .addComponent(txtEndVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(txtCidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtVendedorVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(lblEstadoVenda))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                    .addComponent(lblVlrUnitVenda))
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(txtCodBarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGap(0, 0, Short.MAX_VALUE)))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(txtVlrUnitVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtEstadoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGap(2, 2, 2))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblTelVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblBairroVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblNumVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblSubTotVenda, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtBairroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtTelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtSubTotVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(btnConfirmar, javax.swing.GroupLayout.Alignment.TRAILING))))))))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVendedorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVendedorVenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteVenda)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBairroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairroVenda))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelVenda)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEndVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidadeVenda)
                            .addComponent(lblEstadoVenda))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRefVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRefVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodBarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodBarVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtdVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVlrUnitVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSubTotVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQtdVenda)
                            .addComponent(lblVlrUnitVenda)
                            .addComponent(lblSubTotVenda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkTodosVenda)
                            .addComponent(btnConfirmar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTblItensVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnLimpar)
                    .addComponent(txtTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalVenda))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusLost
        String idCliente = this.cbCliente.getSelectedItem().toString();
        
        if (!idCliente.equals("Nenhum")) {
            try {
                Integer.parseInt(this.cbCliente.getSelectedItem().toString());
                
                ClienteModelo cliente = new ClienteControle().obterCliente2Venda(
                    Integer.parseInt(this.cbCliente.getSelectedItem().toString())
                );

                // Pesquisar se Cod. Existe
                if (cliente !=null )
                {
                    this.txtNome.setText(cliente.getNome());
                    this.txtEndVenda.setText(cliente.getLogradouro());
                    this.txtNumVenda.setText(""+cliente.getNumero());
                    this.txtCidadeVenda.setText(cliente.getCidade());
                    this.txtEstadoVenda.setText(cliente.getEstado());
                    this.txtBairroVenda.setText(cliente.getBairro());
                    this.txtRefVenda.setText(cliente.getReferencia());
                    this.txtTelVenda.setText(cliente.getTelefone());
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Cod. Cliente não Existe!", "Manutencao de Cliente",1);
                    setStatComponents("inicio");
                }   
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(
                        this,
                        "Por favor, Entre com um número válido",
                        "Manutencao de Cliente",
                        1
                );
                limparCampos();
                setStatComponents("inicio");
            }
        } else {
            limparCampos();
        }
    }//GEN-LAST:event_cbClienteFocusLost

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void limparCampos() {
        this.txtVendedorVenda.setText(null);
        this.cbCliente.setSelectedItem("Nenhum");
        this.txtNome.setText(null);
        this.txtEndVenda.setText(null);
        this.txtNumVenda.setText(null);
        this.txtCidadeVenda.setText(null);
        this.txtEstadoVenda.setText(null);
        this.txtBairroVenda.setText(null);
        this.txtRefVenda.setText(null);
        this.txtTelVenda.setText(null);
        this.txtVendedorVenda.requestFocus();;
        setStatComponents("inicio");
    }
    
    private void setStatComponents(String string) {
//        if (string.equals("edicao")) {
//             this.tx.setEnabled(false);
//             this.btnAcao.setText("Alterar");
//        }
//        
//        if (string.equals("inicio")) {
//             this.txtCodCliente.setEnabled(true);
//             this.btnAcao.setText("Salvar");
//        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }
    
    private void iniciaComboBoxFornecedor() {
        ArrayList<ClienteModelo> listaClientes = new ArrayList<ClienteModelo>();
        listaClientes = new ClienteControle().listarCliente();
        
        this.cbCliente.addItem("Nenhum");
        
        for (int i=0;i<=listaClientes.size()-1;i++){
            this.cbCliente.addItem(""+listaClientes.get(i).getIdCliente());
        }        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JCheckBox chkTodosVenda;
    private javax.swing.JLabel lblBairroVenda;
    private javax.swing.JLabel lblCidadeVenda;
    private javax.swing.JLabel lblClienteVenda;
    private javax.swing.JLabel lblCodBarVenda;
    private javax.swing.JLabel lblEndVenda;
    private javax.swing.JLabel lblEstadoVenda;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumVenda;
    private javax.swing.JLabel lblQtdVenda;
    private javax.swing.JLabel lblRefVenda;
    private javax.swing.JLabel lblSubTotVenda;
    private javax.swing.JLabel lblTelVenda;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotalVenda;
    private javax.swing.JLabel lblVendedorVenda;
    private javax.swing.JLabel lblVlrUnitVenda;
    private javax.swing.JScrollPane pnTblItensVenda;
    private javax.swing.JTable tblItensVenda;
    private javax.swing.JTextField txtBairroVenda;
    private javax.swing.JTextField txtCidadeVenda;
    private javax.swing.JTextField txtCodBarVenda;
    private javax.swing.JTextField txtEndVenda;
    private javax.swing.JTextField txtEstadoVenda;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumVenda;
    private javax.swing.JTextField txtQtdVenda;
    private javax.swing.JTextField txtRefVenda;
    private javax.swing.JTextField txtSubTotVenda;
    private javax.swing.JTextField txtTelVenda;
    private javax.swing.JTextField txtTotalVenda;
    private javax.swing.JTextField txtVendedorVenda;
    private javax.swing.JTextField txtVlrUnitVenda;
    // End of variables declaration//GEN-END:variables
}
